apiVersion: v1
kind: Service
metadata:
  name: webserver-service
  labels:
    app: webserver-prem
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30002
    protocol: TCP
    name: grafana-port
  selector:
      app: grafana
      prod: IN